### ISSUE TITLE
Where's the release

### ISSUE THREAD

**Issue by amrshaheen61** [Michael0ne/TOD_tools#2]
Where's the release

**Comment by Michael0ne** [comment]
I can't give any promises, this is my 'hobby' project that I'm doing without any help.
There's still a lot of things to be done and I expect initial 'release' to be near fall 2021.

**Comment by amrshaheen61** [comment]
I want to extract the contents of the archive .main

**Comment by amrshaheen61** [comment]
How I can do that?
@Michael0ne

**Comment by Michael0ne** [comment]
> I want to extract the contents of the archive .main

Please, read readme for the project. I don't have working tools to extract actual game assets.
